import assert from "node:assert/strict";
import {createHash,createHmac} from "node:crypto";
import {readFile} from "node:fs/promises";

const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const publisherSource=await readFile(new URL("../zapier/arc1_publish_preview_pr.js",import.meta.url),"utf8");
const mergeSource=await readFile(new URL("../zapier/arc1_merge_preview_pr.js",import.meta.url),"utf8");
const gateSource=await readFile(new URL("../zapier/arc1_preview_email_gate.js",import.meta.url),"utf8");
const template=await readFile(new URL("../ARC_MASTER_TEMPLATE_V11.html",import.meta.url),"utf8");
const script=(template.match(/<script\b[^>]*>[\s\S]*?<\/script>/gi)||[])[0];
const runPublisher=new AsyncFunction("inputData","fetch","Buffer",publisherSource);
const runMerge=new AsyncFunction("inputData","fetch","Buffer",mergeSource);
const runGate=new AsyncFunction("inputData","fetch","Buffer",gateSource);
const sha=value=>createHash("sha256").update(value,"utf8").digest("hex");
const gitSha=value=>{const bytes=Buffer.from(value,"utf8");return createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex");};
const canonical=value=>{if(value===null||typeof value==="string"||typeof value==="boolean")return JSON.stringify(value);if(typeof value==="number")return JSON.stringify(Object.is(value,-0)?0:value);if(Array.isArray(value))return `[${value.map(canonical).join(",")}]`;return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;};
const mac=(secret,message)=>createHmac("sha256",secret).update(message).digest("hex");

const prefix="a1b2c3d4",folder=`summit-roofing-${prefix}`,branch=`arc-preview/${prefix}`;
const logical=["index.html","services/index.html","about/index.html","process/index.html","contact/index.html"];
const artifact=["about/index.html","contact/index.html","process/index.html","services/index.html","index.html"];
const previewPaths=artifact.map(path=>`${folder}/${path}`),pagesRoot="https://arcwebhq-cpu.github.io/arc-previews";
const linksFor=path=>path==="index.html"?["./","./services/","./about/","./process/","./contact/"]:(()=>{const name=path.split("/")[0];return["../",name==="services"?"./":"../services/",name==="about"?"./":"../about/",name==="process"?"./":"../process/",name==="contact"?"./":"../contact/"];})();
const labels=["Home","Services","About","Process","Contact"];
const pageHtml=(path,{secret="",form=false}={})=>{const links=linksFor(path),nav=className=>`<nav class="${className}" aria-label="menu">${links.map((href,index)=>`<a href="${href}">${labels[index]}</a>`).join("")}</nav>`;return `<!doctype html>\n<html><head><meta name="arc-template-version" content="11.0"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${path}</title>${script}</head><body data-arc-site-mode="preview">${nav("nav-links")}<main><h1>${path}</h1>${form?'<form name="summit-lead" method="POST"><input name="name"><button>Send</button></form>':""}${secret}</main>${nav("footer-links")}<aside class="arc-preview-toolbar" aria-label="ARC preview status"><span><strong>ARC preview</strong>Five-page website concept for this business.</span><span data-arc-checkout-private>Checkout is available only through the private approval email.</span></aside>\n</body>\n</html>\n`;};
const approvalHtml=path=>pageHtml(path).replace(/<aside class="arc-preview-toolbar"[\s\S]*?<\/aside>\n/,"");
const makeArtifacts=({secret="",duplicate=false,oversize=false}={})=>{
  const pages=logical.map((path,index)=>{let published=pageHtml(path,{secret,form:path==="contact/index.html"});if(oversize&&path==="services/index.html")published=published.replace("</main>",`${"x".repeat(151000)}</main>`);const approval=approvalHtml(path);return{key:["home","services","about","process","contact"][index],label:labels[index],path:duplicate&&index===4?"about/index.html":path,repository_path:`${folder}/${duplicate&&index===4?"about/index.html":path}`,url:`${pagesRoot}/${folder}/${path==="index.html"?"":path.replace(/index\.html$/,"")}`,approval_html:approval,approval_sha256:sha(approval),approval_size:Buffer.byteLength(approval),published_html:published,published_sha256:sha(published),published_size:Buffer.byteLength(published),production_sha256:sha(`production:${path}`),production_size:100};});
  const byPath=new Map(pages.map(page=>[page.path,page])),approvalManifest={version:"arc-v11-approval-bundle-v1",pages:logical.map(path=>{const page=byPath.get(path);return page?{path,sha256:page.approval_sha256,size:page.approval_size}:{path,sha256:"0".repeat(64),size:1};})},publishedManifest={version:"arc-v11-published-preview-bundle-v1",pages:artifact.map(path=>{const page=byPath.get(path);return page?{path,sha256:page.published_sha256,size:page.published_size}:{path,sha256:"0".repeat(64),size:1};})};
  const bundle={version:"arc1-five-page-render-bundle-v1",scope:"private-sanitized-five-page-preview-render",runtime_version:"arc1-inject-v11-render-runtime-v1",site_contract_version:"arc-five-page-site-v1",template_version:"11.0",offer_contract_id:"arc-fixed-five-page-offer-v1",deliverable:"fixed-five-page-marketing-website-v1",preview_folder:folder,page_count:5,logical_page_paths:logical,preview_paths:previewPaths,lead_route_mode:"netlify_form",lead_route_form_name:"summit-lead",pages,approval_manifest:approvalManifest,approval_manifest_sha256:sha(canonical(approvalManifest)),published_preview_manifest:publishedManifest,published_preview_bundle_sha256:sha(canonical(publishedManifest)),production_content_sha256:"9".repeat(64)};
  return{bundle,raw:canonical(bundle)};
};
const checkoutSecret="checkout-binding-secret-for-tests-123456789",intakeSecret="intake-evidence-secret-for-tests-123456789",receiptSecret="asset-receipt-secret-for-tests-123456789",customer="owner@example.test",emailToken="email_state_token_abcdefghijklmnopqrstuvwxyz_1234";
const buildInput=(options={})=>{const rendered=makeArtifacts(options),bundleSha=sha(rendered.raw),receipt=canonical({version:"arc1-public-asset-publication-receipt-v1",scope:"github-content-addressed-preview-assets",bridge_contract_sha256:"da1bb4fc84f9871bdec1029d90ff21dfbdabd1e92fe14e838779f06578e426c2",delivery_id:"d".repeat(64),bridge_evidence_sha256:"e".repeat(64),private_asset_receipt_sha256:"f".repeat(64),intake_evidence_sha256:"",intake_state_digest_sha256:"3".repeat(64),asset_manifest_sha256:sha("[]"),asset_permission:"",asset_visual_review_authority_verified:false,asset_visual_review_key_id:"",asset_visual_review_reviewer_id_sha256:"",asset_visual_review_sha256:"",repository:"arcwebhq-cpu/arc-previews",base_branch:"main",preview_branch:branch,pages_base_url:pagesRoot,public_folder_prefix:prefix,preview_folder:folder,entries:[],status:"NO_PUBLIC_UPLOADS"});let receiptObject=JSON.parse(receipt);const intake=canonical({version:"arc1-intake-evidence-v2",scope:"authoritative-first-party-function-intake",offer_contract_id:"arc-fixed-five-page-offer-v1",public_folder_prefix:prefix,state_digest_sha256:"3".repeat(64),submission_data_sha256:"4".repeat(64),state_key:`arc1-intake-claim-v2:${"3".repeat(64)}`}),intakeSha=sha(intake);receiptObject.intake_evidence_sha256=intakeSha;const receiptRaw=canonical(receiptObject),receiptSha=sha(receiptRaw);
  const offer=canonical({version:"arc-checkout-offer-snapshot-v2",scope:"immutable-approved-five-page-preview-private-checkout-offer",offer_contract_id:"arc-fixed-five-page-offer-v1",deliverable:"fixed-five-page-marketing-website-v1",page_count:5,preview_folder:folder,preview_paths:previewPaths,preview_source_repository:"arcwebhq-cpu/arc-previews",public_folder_prefix:prefix,approval_content_sha256:rendered.bundle.approval_manifest_sha256,published_preview_bundle_sha256:rendered.bundle.published_preview_bundle_sha256,production_content_sha256:rendered.bundle.production_content_sha256,render_bundle_sha256:bundleSha,lead_route_mode:"netlify_form",lead_route_form_name:"summit-lead",lead_route_recipient_hmac_sha256:"5".repeat(64),asset_publication_receipt_sha256:receiptSha,checkout_binding_key_id:"01",environment:"arc-production",livemode:false}),offerSha=sha(offer);
  const recipient=canonical({version:"arc1-checkout-recipient-reservation-v2",scope:"private-recipients-for-approved-five-page-checkout",offer_contract_id:"arc-fixed-five-page-offer-v1",deliverable:"fixed-five-page-marketing-website-v1",page_count:5,preview_folder:folder,preview_paths:previewPaths,approval_content_sha256:rendered.bundle.approval_manifest_sha256,published_preview_bundle_sha256:rendered.bundle.published_preview_bundle_sha256,production_content_sha256:rendered.bundle.production_content_sha256,checkout_offer_snapshot_sha256:offerSha,checkout_binding_key_id:"01",stripe_mode:"test",lead_route_mode:"netlify_form",lead_route_form_name:"summit-lead",lead_route_recipient_hmac_sha256:"5".repeat(64),lead_notification_email:"leads@example.test",claim_recipient_email:customer,claim_recipient_email_sha256:sha(customer)}),recipientSha=sha(recipient);
  const renderEvidence=canonical({version:"arc1-render-evidence-v2",scope:"signed-sanitized-five-page-preview-render",offer_contract_id:"arc-fixed-five-page-offer-v1",deliverable:"fixed-five-page-marketing-website-v1",page_count:5,preview_folder:folder,preview_paths:previewPaths,render_bundle_sha256:bundleSha,approval_content_sha256:rendered.bundle.approval_manifest_sha256,content_sha256:rendered.bundle.published_preview_bundle_sha256,published_preview_bundle_sha256:rendered.bundle.published_preview_bundle_sha256,production_content_sha256:rendered.bundle.production_content_sha256,lead_route_mode:"netlify_form",lead_route_form_name:"summit-lead",intake_evidence_sha256:intakeSha,state_digest_sha256:"3".repeat(64),submission_data_sha256:"4".repeat(64),asset_manifest_sha256:sha("[]"),asset_publication_receipt_sha256:receiptSha,script_manifest_sha256:"1ef7f0088cdcf042b1593fbc11d7ea2d3c47e9ff92c94caf2f578179e3993685",checkout_offer_snapshot_sha256:offerSha,checkout_recipient_reservation_sha256:recipientSha});
  return{github_token:"token",validation_pass:true,trusted_event_prefix:prefix,preview_folder:folder,preview_branch:branch,render_bundle_private:rendered.raw,render_bundle_sha256:bundleSha,render_content_sha256:rendered.bundle.published_preview_bundle_sha256,script_manifest_sha256:"1ef7f0088cdcf042b1593fbc11d7ea2d3c47e9ff92c94caf2f578179e3993685",checkout_offer_snapshot_private:offer,checkout_offer_snapshot_sha256:offerSha,checkout_offer_snapshot_hmac_sha256:mac(checkoutSecret,`arc-checkout-offer-snapshot-signature-v2\ntest\n${offer}`),checkout_recipient_reservation_private:recipient,checkout_recipient_reservation_sha256:recipientSha,checkout_recipient_reservation_hmac_sha256:mac(checkoutSecret,`arc1-checkout-recipient-reservation-signature-v2\ntest\n${recipient}`),checkout_binding_key_id:"01",checkout_binding_secret:checkoutSecret,retired_checkout_binding_keys_json:"{}",intake_evidence_private:intake,intake_evidence_sha256:intakeSha,intake_evidence_hmac_sha256:mac(intakeSecret,`arc1-intake-evidence-signature-v2\n${intake}`),intake_evidence_secret:intakeSecret,intake_state_digest_sha256:"3".repeat(64),submission_data_sha256:"4".repeat(64),intake_claim_status:"CLAIMED",intake_claim_state_key:`arc1-intake-claim-v2:${"3".repeat(64)}`,intake_claim_state_digest_sha256:"3".repeat(64),intake_claim_evidence_sha256:intakeSha,intake_claim_public_folder_prefix:prefix,render_evidence_private:renderEvidence,render_evidence_hmac_sha256:mac(intakeSecret,`arc1-render-evidence-signature-v2\n${renderEvidence}`),asset_publication_receipt_private:receiptRaw,asset_publication_receipt_sha256:receiptSha,asset_publication_receipt_hmac_sha256:mac(receiptSecret,`arc1-public-asset-publication-receipt-v1\n${receiptRaw}`),asset_publication_receipt_secret:receiptSecret,customer_email:customer,email_state_token:emailToken,private_lead_notification_email:"leads@example.test"};};

const response=(status,body={},url="",headers={})=>{const raw=status===204?null:typeof body==="string"?body:JSON.stringify(body),all=new Headers(headers);if(raw!==null&&!all.has("content-type"))all.set("content-type","application/json");if(raw!==null&&!all.has("content-length"))all.set("content-length",String(Buffer.byteLength(raw)));const result=new Response(raw,{status,headers:all});Object.defineProperty(result,"url",{value:url});return result;};
class GitHubPagesMock{
  constructor(){this.counter=16;this.blobs=new Map();this.trees=new Map();this.treeFiles=new Map();this.commits=new Map();this.refs=new Map();this.prs=[];this.checkRuns=[];this.pagesMismatchPath="";this.extraPrFile="";const tree=this.buildTree(new Map());this.mainHead="1".repeat(40);this.commits.set(this.mainHead,{tree,files:new Map()});this.refs.set("main",this.mainHead);}
  next(){return(this.counter++).toString(16).padStart(40,"0");}
  buildTree(files){const build=prefix=>{const children=new Map();for(const[path,file]of files){if(prefix&&!path.startsWith(`${prefix}/`))continue;const rest=prefix?path.slice(prefix.length+1):path;if(!rest)continue;const [name,...tail]=rest.split("/");if(!children.has(name))children.set(name,{file:null,nested:false});const item=children.get(name);if(tail.length)item.nested=true;else item.file=file;}const entries=[];for(const[name,item]of [...children].sort(([a],[b])=>a.localeCompare(b))){if(item.nested){const sha=build(prefix?`${prefix}/${name}`:name);entries.push({path:name,mode:"040000",type:"tree",sha});}else entries.push({path:name,mode:"100644",type:"blob",sha:item.file.blobSha,size:Buffer.byteLength(item.file.content)});}const sha=this.next();this.trees.set(sha,entries);return sha;};const root=build("");this.treeFiles.set(root,new Map(files));return root;}
  resolve(ref){return this.refs.get(ref)||ref;}
  async fetch(rawUrl,options={}){const method=options.method||"GET",url=new URL(rawUrl),reply=(status,body={},headers={})=>response(status,body,rawUrl,headers);
    if(url.hostname!=="api.github.com"){const relative=decodeURIComponent(url.pathname).replace(/^\/arc-previews\//,"");const home=relative.endsWith("/")?`${relative}index.html`:relative,shaRef=this.refs.get("main"),file=this.commits.get(shaRef)?.files.get(home);if(!file)return reply(404,"",{"content-type":"text/html"});const body=this.pagesMismatchPath&&home.endsWith(this.pagesMismatchPath)?`${file.content}tamper`:file.content;return reply(200,body,{"content-type":"text/html"});}
    if(method==="POST"&&url.pathname==="/graphql"){const body=JSON.parse(options.body),pr=this.prs.find(item=>item.node_id===body.variables.pullRequestId);pr.draft=false;return reply(200,{data:{markPullRequestReadyForReview:{pullRequest:{number:pr.number,isDraft:false,headRefOid:pr.head.sha}}}});}
    const check=url.pathname.match(/\/commits\/([a-f0-9]{40})\/check-runs$/);if(method==="GET"&&check)return reply(200,{total_count:this.checkRuns.length,check_runs:this.checkRuns});
    const merge=url.pathname.match(/\/pulls\/(\d+)\/merge$/);if(method==="PUT"&&merge){const pr=this.prs[0],body=JSON.parse(options.body);if(body.sha!==pr.head.sha)return reply(409,{message:"head"});const source=this.commits.get(pr.head.sha),sha=this.next();this.commits.set(sha,{tree:source.tree,files:new Map(source.files)});this.refs.set("main",sha);this.mainHead=sha;pr.state="closed";pr.merged_at="2026-08-25T20:00:00.000Z";pr.merge_commit_sha=sha;return reply(200,{merged:true,sha,message:"Merged"});}
    const files=url.pathname.match(/\/pulls\/(\d+)\/files$/);if(method==="GET"&&files){const list=previewPaths.map(filename=>({filename,status:"added"}));if(this.extraPrFile)list.push({filename:this.extraPrFile,status:"added"});return reply(200,list);}
    const pull=url.pathname.match(/\/pulls\/(\d+)$/);if(method==="GET"&&pull){const pr=this.prs.find(item=>item.number===Number(pull[1]));return pr?reply(200,pr):reply(404,{message:"Not Found"});}if(method==="PATCH"&&pull){const pr=this.prs[0];Object.assign(pr,JSON.parse(options.body));return reply(200,pr);}
    if(url.pathname.endsWith("/pulls")&&method==="GET")return reply(200,this.prs);if(url.pathname.endsWith("/pulls")&&method==="POST"){const body=JSON.parse(options.body),head=this.refs.get(branch),pr={number:42,node_id:"PR42",html_url:"https://github.com/arcwebhq-cpu/arc-previews/pull/42",state:"open",draft:body.draft,merged_at:null,merge_commit_sha:null,base:{ref:body.base},head:{ref:body.head,sha:head}};this.prs=[pr];return reply(201,pr);}
    const ref=url.pathname.match(/\/git\/ref\/heads%2F(.+)$/);if(method==="GET"&&ref){const name=decodeURIComponent(ref[1]),sha=this.refs.get(name);return sha?reply(200,{object:{sha}}):reply(404,{message:"Not Found"});}
    const commit=url.pathname.match(/\/git\/commits\/([a-f0-9]{40})$/);if(method==="GET"&&commit){const item=this.commits.get(commit[1]);return item?reply(200,{tree:{sha:item.tree}}):reply(404,{message:"Not Found"});}
    const tree=url.pathname.match(/\/git\/trees\/([a-f0-9]{40})$/);if(method==="GET"&&tree)return this.trees.has(tree[1])?reply(200,{tree:this.trees.get(tree[1])}):reply(404,{message:"Not Found"});
    const contentIndex=url.pathname.indexOf("/contents/");if(method==="GET"&&contentIndex>=0){const path=decodeURIComponent(url.pathname.slice(contentIndex+10)),refName=url.searchParams.get("ref"),commitSha=this.resolve(refName),file=this.commits.get(commitSha)?.files.get(path);return file?reply(200,{content:Buffer.from(file.content).toString("base64")}):reply(404,{message:"Not Found"});}
    if(method==="POST"&&url.pathname.endsWith("/git/blobs")){const body=JSON.parse(options.body),content=Buffer.from(body.content,"base64").toString("utf8"),sha=gitSha(content);this.blobs.set(sha,content);return reply(201,{sha});}
    if(method==="POST"&&url.pathname.endsWith("/git/trees")){const body=JSON.parse(options.body),files=new Map(this.treeFiles.get(body.base_tree)||[]);for(const entry of body.tree)files.set(entry.path,{blobSha:entry.sha,content:this.blobs.get(entry.sha)});const sha=this.buildTree(files);return reply(201,{sha});}
    if(method==="POST"&&url.pathname.endsWith("/git/commits")){const body=JSON.parse(options.body),sha=this.next(),files=new Map(this.treeFiles.get(body.tree)||[]);this.commits.set(sha,{tree:body.tree,files});return reply(201,{sha});}
    if(method==="POST"&&url.pathname.endsWith("/git/refs")){const body=JSON.parse(options.body),name=body.ref.replace("refs/heads/","");if(this.refs.has(name))return reply(422,{message:"exists"});this.refs.set(name,body.sha);return reply(201,{object:{sha:body.sha}});}
    const patchRef=url.pathname.match(/\/git\/refs\/heads%2F(.+)$/);if(method==="PATCH"&&patchRef){const name=decodeURIComponent(patchRef[1]),body=JSON.parse(options.body);this.refs.set(name,body.sha);for(const pr of this.prs)if(pr.head.ref===name)pr.head.sha=body.sha;return reply(200,{object:{sha:body.sha}});}
    return reply(404,{message:`Unhandled ${method} ${url.pathname}`});
  }
}

const noNetwork=()=>{throw new Error("unexpected network");};
const legacyBase=buildInput();for(const key of ["html_content","file_path","preview_path"]){await assert.rejects(runPublisher({...legacyBase,[key]:"legacy"},noNetwork,Buffer),/legacy singular input/);}
const mixed=buildInput(),legacyOffer=canonical({...JSON.parse(mixed.checkout_offer_snapshot_private),version:"arc-checkout-offer-snapshot-v1"});await assert.rejects(runPublisher({...mixed,checkout_offer_snapshot_private:legacyOffer,checkout_offer_snapshot_sha256:sha(legacyOffer)},noNetwork,Buffer),/v2 checkout offer snapshot/);
const missing=buildInput();{const bundle=JSON.parse(missing.render_bundle_private);bundle.pages.pop();missing.render_bundle_private=canonical(bundle);missing.render_bundle_sha256=sha(missing.render_bundle_private);await assert.rejects(runPublisher(missing,noNetwork,Buffer),/exactly five pages/);}
const duplicate=buildInput({duplicate:true});await assert.rejects(runPublisher(duplicate,noNetwork,Buffer),/digest\/path\/size binding/);
const oversized=buildInput({oversize:true});await assert.rejects(runPublisher(oversized,noNetwork,Buffer),/digest\/path\/size binding/);
const privacy=buildInput({secret:customer});await assert.rejects(runPublisher(privacy,noNetwork,Buffer),/ARC_PRIVACY_FAILED/);
const tamper=buildInput();{const bundle=JSON.parse(tamper.render_bundle_private),page=bundle.pages.find(item=>item.path==="services/index.html");page.published_html=page.published_html.replace("services/index.html</h1>","tampered</h1>");tamper.render_bundle_private=canonical(bundle);tamper.render_bundle_sha256=sha(tamper.render_bundle_private);await assert.rejects(runPublisher(tamper,noNetwork,Buffer),/digest\/path\/size binding/);}

const input=buildInput(),mock=new GitHubPagesMock(),publish=await runPublisher(input,mock.fetch.bind(mock),Buffer);assert.equal(publish.status,"PR_CREATED");assert.equal(publish.page_count,5);assert.deepEqual(publish.preview_paths,previewPaths);assert.equal(publish.content_sha256,publish.published_preview_bundle_sha256);assert.equal(publish.send_preview_email,false);assert.equal(publish.private_checkout_link_allowed,false);assert.equal(Object.hasOwn(publish,"file_path"),false);
mock.checkRuns=[{id:7,name:"ARC preview quality/preview-quality",head_sha:publish.head_sha,status:"completed",conclusion:"success",app:{slug:"github-actions",id:15368}}];
const mergeInput={...input,head_sha:publish.head_sha,head_tree_sha:publish.head_tree_sha,pr_number:publish.pr_number};const merged=await runMerge(mergeInput,mock.fetch.bind(mock),Buffer);assert.equal(merged.status,"MERGED");const proof=JSON.parse(merged.merge_proof);assert.equal(proof.version,"arc-preview-merge-proof-v2");assert.deepEqual(proof.preview_paths,previewPaths);assert.equal(proof.source_tree_sha,proof.head_tree_sha);
// Unrelated main movement is allowed when this preview folder remains exact.
const oldMain=mock.commits.get(mock.mainHead),unrelatedFiles=new Map(oldMain.files);unrelatedFiles.set("README.md",{blobSha:gitSha("unrelated"),content:"unrelated"});mock.blobs.set(gitSha("unrelated"),"unrelated");const unrelatedTree=mock.buildTree(unrelatedFiles),unrelatedSha=mock.next();mock.commits.set(unrelatedSha,{tree:unrelatedTree,files:unrelatedFiles});mock.refs.set("main",unrelatedSha);mock.mainHead=unrelatedSha;
const gateInput={...mergeInput,merge_proof:merged.merge_proof};const ready=await runGate(gateInput,mock.fetch.bind(mock),Buffer);assert.equal(ready.status,"PRIVATE_CHECKOUT_CONTENT_READY");assert.equal(ready.send_preview_email,false);assert.equal(ready.outbox_write_allowed,false);assert.equal(ready.email_authorization_allowed,false);assert.equal(ready.checkout_url_exposure_allowed,false);const core=JSON.parse(ready.checkout_readiness_core_private),observation=JSON.parse(ready.checkout_readiness_observation_private);
assert.deepEqual(Object.keys(core).sort(),["approval_content_sha256","asset_publication_receipt_sha256","check_app_id","check_app_slug","check_name","checkout_offer_snapshot_sha256","checkout_recipient_reservation_sha256","content_sha256","customer_email_sha256","deliverable","email_state_token_sha256","head_sha","lead_route_form_name","lead_route_mode","lead_route_recipient_hmac_sha256","merge_commit_sha","merged_at","offer_contract_id","page_count","pr_number","preview_folder","preview_paths","preview_url","published_preview_bundle_sha256","published_site_sha256","render_bundle_sha256","repository","scope","script_manifest_sha256","source_tree_sha","version"].sort());
assert.equal(core.version,"arc1-preview-readiness-core-v2");assert.equal(core.offer_contract_id,"arc-fixed-five-page-offer-v1");assert.equal(core.deliverable,"fixed-five-page-marketing-website-v1");assert.equal(core.page_count,5);assert.equal(core.content_sha256,core.published_preview_bundle_sha256);assert.equal(core.published_site_sha256,"9".repeat(64));assert.equal(core.lead_route_recipient_hmac_sha256,"5".repeat(64));
assert.deepEqual(Object.keys(observation).sort(),["current_main_published_preview_bundle_sha256","current_main_sha","current_main_tree_sha","expires_at","issued_at","pages_published_preview_bundle_sha256","preview_folder","preview_paths","published_site_sha256","readiness_core_sha256","repository","scope","version"].sort());assert.equal(observation.version,"arc1-preview-readiness-observation-v2");assert.notEqual(observation.current_main_tree_sha,core.source_tree_sha);assert.equal(observation.current_main_published_preview_bundle_sha256,core.published_preview_bundle_sha256);assert.equal(observation.pages_published_preview_bundle_sha256,core.published_preview_bundle_sha256);

const pagesMismatch=new GitHubPagesMock();const pub2=await runPublisher(input,pagesMismatch.fetch.bind(pagesMismatch),Buffer);pagesMismatch.checkRuns=[{id:8,name:"ARC preview quality/preview-quality",head_sha:pub2.head_sha,status:"completed",conclusion:"success",app:{slug:"github-actions",id:15368}}];const merge2=await runMerge({...input,head_sha:pub2.head_sha,head_tree_sha:pub2.head_tree_sha,pr_number:pub2.pr_number},pagesMismatch.fetch.bind(pagesMismatch),Buffer);pagesMismatch.pagesMismatchPath="process/index.html";const waiting=await runGate({...input,head_sha:pub2.head_sha,head_tree_sha:pub2.head_tree_sha,pr_number:pub2.pr_number,merge_proof:merge2.merge_proof},pagesMismatch.fetch.bind(pagesMismatch),Buffer);assert.equal(waiting.status,"WAITING_FOR_PAGES");assert.equal(waiting.send_preview_email,false);

const extraMock=new GitHubPagesMock(),pub3=await runPublisher(input,extraMock.fetch.bind(extraMock),Buffer);extraMock.checkRuns=[{id:9,name:"ARC preview quality/preview-quality",head_sha:pub3.head_sha,status:"completed",conclusion:"success",app:{slug:"github-actions",id:15368}}];extraMock.extraPrFile=`${folder}/extra.html`;await assert.rejects(runMerge({...input,head_sha:pub3.head_sha,head_tree_sha:pub3.head_tree_sha,pr_number:pub3.pr_number},extraMock.fetch.bind(extraMock),Buffer),/exact PR file vector/);

assert.doesNotMatch(publisherSource,/ARC_PREVIEW_PROOF_START|arc-template-version[^\n]*10\\\.0/);assert.match(publisherSource,/arc1-five-page-render-bundle-v1/);assert.match(mergeSource,/arc-preview-merge-proof-v2/);assert.match(gateSource,/arc1-preview-readiness-core-v2/);assert.match(gateSource,/arc1-preview-readiness-observation-v2/);
console.log("ARC1 exact five-page PR/merge/Pages readiness contract tests passed.");
